[tool.poetry]
name = "jaffle_shop"
version = "0.1.0"
description = ""
authors = ["Ramzi"]

[tool.poetry.dependencies]
python = "^3.8"
dbt = "0.19"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
